output "access_key_id" {
  description = "The access key ID that identifies the temporary security credentials."
  value       = local.result.Credentials.AccessKeyId
}

output "expiration" {
  description = "The date on which the current credentials expire."
  value       = local.result.Credentials.Expiration
}

output "secret_access_key" {
  description = "The secret access key that can be used to sign requests."
  value       = local.result.Credentials.SecretAccessKey
}

output "session_token" {
  description = "The token that users must pass to the service API to use the temporary credentials."
  value       = local.result.Credentials.SessionToken
}

output "assumed_role_user_arn" {
  description = "The ARN of the temporary security credentials that are returned from the AssumeRole action."
  value       = local.result.AssumedRoleUser.Arn
}

output "assumed_role_id" {
  description = "A unique identifier that contains the role ID and the role session name of the role that is being assumed. The role ID is generated by AWS when the role is created."
  value       = local.result.AssumedRoleUser.AssumedRoleId
}

output "role_session_name" {
  description = "The role session name (a UUID if this was not provided as an input value)."
  value       = local.role_session_name
}
